"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

from dotenv import load_dotenv
import os

# Cargar variables de entorno
load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'vehicles',
    'maintenance',
    'backoffice'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                
                'config.context_processors.active_page'
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGGING = {
    'version': 1,
    
    # No deshabilitar loggers existentes (importante para que funcionen los de Django/libs)
    'disable_existing_loggers': False,

    # --- Cómo se verán los mensajes ---
    'formatters': {
        'verbose': {
            # Formato detallado: Nivel, Fecha/Hora, Módulo, Mensaje
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            # Formato simple: Nivel, Mensaje
            'format': '{levelname} {message}',
            'style': '{',
        },
    },

    # --- Dónde enviar los mensajes ---
    'handlers': {
        'console': {
            # Enviar a la consola (terminal)
            'class': 'logging.StreamHandler',
            # Usar el formato detallado
            'formatter': 'verbose', 
        },
    },

    # --- Qué loggers configurar ---
    'loggers': {
        # --- Loggers de Bibliotecas (Menos detalle) ---
        'django': {
            'handlers': ['console'],
            'level': 'INFO', # Mostrar solo INFO, WARNING, ERROR, CRITICAL para Django
            'propagate': False, # No pasar mensajes de Django al logger 'root'
        },
        'supabase': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'httpx': {
            'handlers': ['console'],
            'level': 'INFO',
             'propagate': False,
        },
        # --- Loggers de Tus Aplicaciones ---
        'accounts': { 
            'handlers': ['console'], # Enviar logs de 'accounts' a la consola
            'level': 'DEBUG',       # Mostrar DEBUG, INFO, WARNING, ERROR, CRITICAL
            'propagate': False,      # Puedes poner True si quieres que también vayan al root
        },
        'vehicles': { 
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'maintenance': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'backoffice': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        # Añade aquí otras apps tuyas si las tienes...
    },
    
    # --- Logger Raíz (Captura todo lo demás) ---
    'root': {
        'handlers': ['console'], # Enviar logs no capturados a la consola
        'level': 'INFO',         # Nivel por defecto para logs no específicos (ej. warnings de librerías no listadas)
    },


}
